const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('retroPlayer', {
  chooseLibrary: () => ipcRenderer.invoke('library:choose'),
  loadSavedLibrary: () => ipcRenderer.invoke('library:saved'),
  loadIndexedLibrary: (directory) => ipcRenderer.invoke('library:indexed', directory),
  rescanLibrary: () => ipcRenderer.invoke('library:rescan'),
  scanLibrary: (directory) => ipcRenderer.invoke('library:scan', directory),
  loadLibraryTree: (directory) => ipcRenderer.invoke('library:tree', directory),
  loadFolder: (directory) => ipcRenderer.invoke('library:load-folder', directory),
  savePlaylist: (payload) => ipcRenderer.invoke('playlists:save', payload),
  listPlaylists: () => ipcRenderer.invoke('playlists:list'),
  loadPlaylistTracks: (playlistId) => ipcRenderer.invoke('playlists:tracks', playlistId),
  importAppleMusicPlaylists: () => ipcRenderer.invoke('playlists:import-apple-music'),
  deletePlaylist: (playlistId) => ipcRenderer.invoke('playlists:delete', playlistId),
  recordPlaybackEvent: (payload) => ipcRenderer.invoke('telemetry:record', payload),
  recommendRadioTrack: (payload) => ipcRenderer.invoke('radio:recommend', payload),
  recordRadioFeedback: (anchorPath, candidatePath, vote) => ipcRenderer.invoke('radio:feedback', anchorPath, candidatePath, vote),
  savePlaybackSession: (payload) => ipcRenderer.invoke('playback-session:update', payload),
  restorePlaybackSession: () => ipcRenderer.invoke('playback-session:restore'),
  setAlwaysOnTop: (value) => ipcRenderer.invoke('window:always-on-top', value),
  getKeepAwake: () => ipcRenderer.invoke('window:keep-awake'),
  setKeepAwake: (value) => ipcRenderer.invoke('window:keep-awake', value),
  triggerHaptic: (pattern) => ipcRenderer.send('haptics:trigger', pattern),
  setCompact: (value) => ipcRenderer.invoke('window:compact', value),
  getSystemVolume: () => ipcRenderer.invoke('system-volume:get'),
  setSystemVolume: (value) => ipcRenderer.invoke('system-volume:set', value),
  nativeAudioCommand: (action, payload) => ipcRenderer.invoke('native-audio:command', action, payload),
  prepareSmartFade: (current, next) => ipcRenderer.invoke('smart-fade:prepare', current, next),
  onNativeAudioState: (callback) => ipcRenderer.on('native-audio:state', (_event, state) => callback(state))
});
